### ISSUE TITLE
Menu issue in Edge

### ISSUE THREAD

**Issue by feeohnah** [codrops/BlockRevealers#2]
No error messages, content is loaded, just doesn't reveal the items, all you see is the background. 

<img width="1278" alt="screen shot 2017-03-09 at 7 02 10 pm" src="https://cloud.githubusercontent.com/assets/2460068/23749481/f85b7db4-04fa-11e7-953d-a1c804f9b2b6.png">

**Comment by cartogram** [comment]
I think that is an issue with using opacity on the outer element and edge not creating a new stacking context.

**Comment by cartogram** [comment]
Opened a PR https://github.com/codrops/BlockRevealers/pull/3

**Comment by crnacura** [comment]
Thanks a lot for the PR! I've updated the repo with a mix of your solution and some positioning so that we don't have to use the scale. Work fine in Edge now :)
